name: Documentation
on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/docs.yaml"
      - "docs/**"

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0  # Fetch all branches to include 'gh-pages' branch
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: 3.x
      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
        with:
          key: mkdocs-material-${{ github.ref }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: Install dependencies
        run: pip install mkdocs-material mike

      - name: Lint Markdown files
        uses: DavidAnson/markdownlint-cli2-action@ded1f9488f68a970bc66ea5619e13e9b52e601cd # v23
        with:
          config: 'docs/.markdownlint.jsonc'
          globs: 'docs/**/*.md'

      - name: Build pages
        run: mkdocs build --strict

      - name: Configure Git user
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Deploy pages (unstable)
        if: github.ref == 'refs/heads/main'
        run: mike deploy --push --update-aliases unstable

      - name: Deploy pages (new release)
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          mike deploy --push --update-aliases ${{ github.ref_name }} latest
          echo "Deployed version ${{ github.ref_name }} to GitHub Pages"
